# Generated by Django 5.2.9 on 2025-12-17 05:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenCharter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=200, verbose_name="सेवाको नाम"),
                ),
                ("required_docs", models.TextField(verbose_name="आवश्यक कागजात")),
                (
                    "service_time",
                    models.CharField(max_length=100, verbose_name="लाग्ने समय"),
                ),
                (
                    "service_fee",
                    models.CharField(max_length=100, verbose_name="सेवा शुल्क"),
                ),
                (
                    "responsible_officer",
                    models.CharField(
                        max_length=100, verbose_name="जिम्मेवार अधिकारी / शाखा"
                    ),
                ),
            ],
            options={
                "verbose_name": "नागरिक वडापत्र",
                "verbose_name_plural": "नागरिक वडापत्र",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="यन्त्रको नाम")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP ठेगाना"
                    ),
                ),
                (
                    "location_description",
                    models.CharField(max_length=200, verbose_name="राखेको स्थान"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="सक्रिय")),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="अन्तिम पटक देखिएको"
                    ),
                ),
            ],
            options={
                "verbose_name": "डिजिटल सूचना पाटी",
                "verbose_name_plural": "डिजिटल सूचना पाटीहरू",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="एल्बमको नाम")),
                ("description", models.TextField(blank=True, verbose_name="विवरण")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "फोटो ग्यालरी",
                "verbose_name_plural": "फोटो ग्यालरी",
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="कार्यालयको नाम"),
                ),
                (
                    "is_ward",
                    models.BooleanField(
                        default=False, verbose_name="वार्ड कार्यालय हो?"
                    ),
                ),
                (
                    "ward_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="वार्ड नं."
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="ठेगाना")),
            ],
            options={
                "verbose_name": "कार्यालय / वार्ड",
                "verbose_name_plural": "कार्यालयहरू",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "प्रणाली प्रशासक (System Admin)"),
                            ("cao", "प्रमुख प्रशासकीय अधिकृत (CAO)"),
                            ("section_head", "शाखा प्रमुख (Section Head)"),
                            ("staff", "कर्मचारी (Staff)"),
                        ],
                        default="staff",
                        max_length=20,
                        verbose_name="भूमिका",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "प्रयोगकर्ता",
                "verbose_name_plural": "प्रयोगकर्ताहरू",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=50)),
                ("object_id", models.CharField(max_length=50, null=True)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "सम्परीक्षण लग",
                "verbose_name_plural": "सम्परीक्षण लगहरू",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="सूचनाको शीर्षक"),
                ),
                ("content", models.TextField(verbose_name="सूचनाको विवरण")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "सामान्य (Normal)"),
                            ("high", "उच्च (High)"),
                            ("emergency", "आपतकालीन (Emergency)"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="प्राथमिकता",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "मस्यौदा (Draft)"),
                            ("recommended", "सिफारिस गरिएको (Recommended)"),
                            ("approved", "स्वीकृत (Approved)"),
                            ("published", "प्रकाशन गरिएको (Published)"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="स्थिति",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="प्रकाशन मिति"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_notices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="स्वीकृत गर्ने",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="सिर्जनाकर्ता",
                    ),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommended_notices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="सिफारिस गर्ने",
                    ),
                ),
                (
                    "target_devices",
                    models.ManyToManyField(
                        to="core.device", verbose_name="प्रकाशन हुने पाटीहरू"
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.office",
                        verbose_name="सम्बन्धित कार्यालय",
                    ),
                ),
            ],
            options={
                "verbose_name": "सूचना",
                "verbose_name_plural": "सूचनाहरू",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/", verbose_name="फोटो")),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="क्याप्सन"
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.gallery",
                    ),
                ),
            ],
            options={
                "verbose_name": "फोटो",
            },
        ),
    ]
