# Generated by Django 5.1.15 on 2025-12-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="gallery/covers/",
                verbose_name="कभर फोटो",
            ),
        ),
    ]
