# Generated by Django 5.1.15 on 2025-12-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_gallery_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="office",
        ),
        migrations.AddField(
            model_name="notice",
            name="office",
            field=models.ManyToManyField(
                to="core.office", verbose_name="सम्बन्धित कार्यालय"
            ),
        ),
    ]
