# Generated by Django 5.1.15 on 2025-12-18 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_notice_office_notice_office"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizencharter",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="सिर्जनाकर्ता",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="सिर्जनाकर्ता",
            ),
        ),
    ]
