# Generated by Django 5.2.9 on 2025-12-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_citizencharter_created_by_gallery_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="font_size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                max_length=10,
                verbose_name="Font Size",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="theme_mode",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
                verbose_name="Theme Mode",
            ),
        ),
    ]
