# Generated by Django 5.2.9 on 2025-12-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_font_size_user_theme_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="फोन नं."
            ),
        ),
    ]
