# Generated by Django 5.2.9 on 2025-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="समाप्ति मिति"),
        ),
    ]
