# Generated by Django 5.2.9 on 2025-12-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_notice_expiry_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="पूरा नाम"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="फोन नं."),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="पद"),
                ),
                (
                    "office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.office",
                        verbose_name="कार्यालय",
                    ),
                ),
            ],
            options={
                "verbose_name": "सम्पर्क",
                "verbose_name_plural": "सम्पर्कहरू",
            },
        ),
    ]
