# Generated by Django 5.2.9 on 2025-12-18 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_contact_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="मोडलको नाम"),
                ),
                ("object_id", models.IntegerField(verbose_name="अब्जेक्ट ID")),
                (
                    "object_title",
                    models.CharField(max_length=255, verbose_name="शीर्षक/नाम"),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("edit", "सम्पादन (Edit)"),
                            ("delete", "हटाउनुहोस् (Delete)"),
                        ],
                        max_length=20,
                        verbose_name="अनुरोधको प्रकार",
                    ),
                ),
                ("reason", models.TextField(verbose_name="कारण")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "बाँकी (Pending)"),
                            ("completed", "पूरा भयो (Completed)"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="स्थिति",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="सिर्जना गरिएको मिति"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="अनुरोधकर्ता",
                    ),
                ),
            ],
            options={
                "verbose_name": "कार्य अनुरोध",
                "verbose_name_plural": "कार्य अनुरोधहरू",
                "ordering": ["-created_at"],
            },
        ),
    ]
