# Generated by Django 4.2 on 2025-12-22 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_actionrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="टिकट नं."
                    ),
                ),
                (
                    "citizen_name",
                    models.CharField(max_length=100, verbose_name="नागरिकको नाम"),
                ),
                (
                    "citizen_phone",
                    models.CharField(max_length=15, verbose_name="फोन नं."),
                ),
                (
                    "grievance_type",
                    models.CharField(
                        choices=[
                            ("complaint", "गुनासो (Complaint)"),
                            ("suggestion", "सुझाव (Suggestion)"),
                            ("grievance", "बाधा (Grievance)"),
                        ],
                        default="complaint",
                        max_length=20,
                        verbose_name="प्रकार",
                    ),
                ),
                ("description", models.TextField(verbose_name="विवरण")),
                (
                    "attachment",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="grievances/",
                        verbose_name="संलग्न कागजात",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "प्रक्रियामा (Pending)"),
                            ("processing", "कारबाही हुँदै (Processing)"),
                            ("resolved", "समाधान भयो (Resolved)"),
                            ("rejected", "अस्वीकृत (Rejected)"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="स्थिति",
                    ),
                ),
                (
                    "response_details",
                    models.TextField(blank=True, verbose_name="प्रतिक्रिया विवरण"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="पेश गरिएको मिति"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="जिम्मेवार अधिकारी",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.office",
                        verbose_name="सम्बन्धित कार्यालय",
                    ),
                ),
            ],
            options={
                "verbose_name": "गुनासो तथा सुझाव",
                "verbose_name_plural": "गुनासो तथा सुझावहरू",
                "ordering": ["-created_at"],
            },
        ),
    ]
