# Generated by Django 4.2 on 2025-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_grievance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "प्रणाली प्रशासक (System Admin)"),
                    ("cao", "प्रमुख प्रशासकीय अधिकृत (CAO)"),
                    ("section_head", "शाखा प्रमुख (Section Head)"),
                    ("grievance_officer", "गुनासो अधिकारी (Grievance Officer)"),
                    ("staff", "कर्मचारी (Staff)"),
                ],
                default="staff",
                max_length=20,
                verbose_name="भूमिका",
            ),
        ),
    ]
