# Generated by Django 4.2 on 2025-12-28 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="cover_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="gallery/covers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "mp4", "webm", "ogg"]
                    )
                ],
                verbose_name="कभर फोटो / भिडियो",
            ),
        ),
    ]
