# Generated by Django 4.2 on 2025-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_gallery_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="duration",
            field=models.PositiveIntegerField(
                default=10,
                help_text="कति सेकेन्ड सम्म देखाउने? (Duration in seconds)",
                verbose_name="देखाउने समय (सेकेन्डमा)",
            ),
        ),
    ]
