# Generated by Django 5.2.9 on 2025-12-28 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gallery_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='समाचार/सूचना (Message)')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय (Active)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='क्रम (Order)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='सिर्जनाकर्ता')),
            ],
            options={
                'verbose_name': 'टिकर सन्देश',
                'verbose_name_plural': 'टिकर सन्देशहरू',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
