# Generated by Django 4.2 on 2026-01-08 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_tickermessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="आयोजनाको नाम"),
                ),
                ("description", models.TextField(blank=True, verbose_name="विवरण")),
                ("start_date", models.DateField(verbose_name="सुरु मिति")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="सम्पन्न मिति"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "बाँकी (Pending)"),
                            ("active", "सक्रिय (Active)"),
                            ("completed", "सम्पन्न (Completed)"),
                            ("cancelled", "रद्द गरिएको (Cancelled)"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="स्थिति",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="सिर्जनाकर्ता",
                    ),
                ),
            ],
            options={
                "verbose_name": "आयोजना",
                "verbose_name_plural": "आयोजनाहरू",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="प्रतिवेदन मिति")),
                ("tasks_completed", models.TextField(verbose_name="सम्पन्न कार्यहरू")),
                ("plan_next_day", models.TextField(verbose_name="भोलिको योजना")),
                (
                    "issues_challenges",
                    models.TextField(blank=True, verbose_name="समस्या/चुनौतीहरू"),
                ),
                (
                    "is_submitted",
                    models.BooleanField(default=False, verbose_name="बुझाइएको"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="core.project",
                        verbose_name="सम्बन्धित आयोजना",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="कर्मचारी",
                    ),
                ),
            ],
            options={
                "verbose_name": "दैनिक कार्य प्रतिवेदन",
                "verbose_name_plural": "दैनिक कार्य प्रतिवेदनहरू",
                "ordering": ["-report_date"],
                "unique_together": {("user", "report_date")},
            },
        ),
    ]
