# Generated by Django 4.2 on 2026-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_project_dailyreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allocation_source",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="विनियोजन स्रोत (Source)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_allocation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="बजेट विनियोजन (Budget)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_head",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="बजेट शीर्षक (Budget Head)"
            ),
        ),
    ]
