# Generated by Django 4.2 on 2026-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_project_allocation_source_project_budget_allocation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="activity_breakdown",
            field=models.TextField(
                blank=True,
                help_text="List main activities and their specific progress",
                verbose_name="क्रियाकलाप विवरण (Activity Breakdown)",
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="financial_progress",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount spent today",
                max_digits=12,
                null=True,
                verbose_name="वित्तीय प्रगति (Financial)",
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="physical_progress",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage (0-100)",
                max_digits=5,
                null=True,
                verbose_name="भौतिक प्रगति (Physical %)",
            ),
        ),
    ]
