# Generated by Django 4.2 on 2026-01-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_dailyreport_activity_breakdown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget_q1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="प्र. त्रै. बजेट (Q1)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_q2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="दो. त्रै. बजेट (Q2)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_q3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="ते. त्रै. बजेट (Q3)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_q4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="चौ. त्रै. बजेट (Q4)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="expenditure_head",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="खर्च शीर्षक (Exp. Head)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="fiscal_year",
            field=models.CharField(
                default="2081/82", max_length=20, verbose_name="आर्थिक वर्ष"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="measure_unit",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="इकाई (Unit)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_method",
            field=models.CharField(
                blank=True,
                default="cash",
                max_length=50,
                verbose_name="भुक्तानी विधि (Payment)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="बजेट उपशीर्षक (Project Code)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sector",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="क्षेत्र (Sector)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sub_sector",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="उप क्षेत्र (Sub-Sector)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_group",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="लक्षित समूह (Target Group)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_q1",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="प्र. त्रै. (Q1)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_q2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="दो. त्रै. (Q2)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_q3",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ते. त्रै. (Q3)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_q4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="चौ. त्रै. (Q4)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="जम्मा लक्ष्य (Total Target)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Project Name (English)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="unit_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="प्रति इकाई दर (Rate)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget_allocation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="कुल बजेट (Total Budget)",
            ),
        ),
    ]
