# Generated by Django 4.2 on 2026-01-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_project_budget_q1_project_budget_q2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="विनियोजन स्रोत (Source)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenditureHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="खर्च शीर्षक (Exp. Head)"
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="कोड")),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="क्षेत्र (Sector)"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="allocation_source",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="विनियोजन स्रोत (Source)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="expenditure_head",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="खर्च शीर्षक (Exp. Head)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sector",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="क्षेत्र (Sector)"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sub_sector",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="उप क्षेत्र (Sub-Sector)",
            ),
        ),
        migrations.CreateModel(
            name="SubSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="उप क्षेत्र (Sub-Sector)"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_sectors",
                        to="core.sector",
                    ),
                ),
            ],
        ),
    ]
