# Generated by Django 4.2 on 2026-01-09 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_allocationsource_expenditurehead_sector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="allocation_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.allocationsource",
                verbose_name="विनियोजन स्रोत (Source)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="expenditure_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.expenditurehead",
                verbose_name="खर्च शीर्षक (Exp. Head)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sector",
                verbose_name="क्षेत्र (Sector)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="sub_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subsector",
                verbose_name="उप क्षेत्र (Sub-Sector)",
            ),
        ),
    ]
