# Generated by Django 4.2 on 2026-01-09 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_project_allocation_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_name",
                    models.CharField(max_length=255, verbose_name="कार्यक्रमको नाम"),
                ),
                (
                    "budget_heading_no",
                    models.CharField(max_length=50, verbose_name="बजेट शीर्षक नं."),
                ),
                (
                    "approved_budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="स्वीकृत बजेट"
                    ),
                ),
                (
                    "ward",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="वडा / क्षेत्र",
                    ),
                ),
                (
                    "implementation_method",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="कार्यान्वयन विधि",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        verbose_name="क्रियाकलापको विवरण (Activity Description)"
                    ),
                ),
                (
                    "budget_heading_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="बजेट शीर्षक नं."
                    ),
                ),
                (
                    "expense_today",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="आजको खर्च (Today's Expense)",
                    ),
                ),
                (
                    "physical_output",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="भौतिक प्रगति (Physical Output)",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="प्रगति प्रतिशत (%)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyProgressReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="प्रतिवेदन मिति (Date)")),
                (
                    "date_np",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="मिति (नेपाली)"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="शाखा / वडा (Section)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_reports",
                        to="core.project",
                        verbose_name="आयोजना (Project)",
                    ),
                ),
                (
                    "reporting_officer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="प्रतिवेदन गर्ने कर्मचारी",
                    ),
                ),
            ],
            options={
                "verbose_name": "दैनिक प्रगति प्रतिवेदन",
                "verbose_name_plural": "दैनिक प्रगति प्रतिवेदनहरू",
                "unique_together": {("project", "date", "section")},
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fy_name",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="आर्थिक वर्ष (Fiscal Year)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="सुरु मिति")),
                ("end_date", models.DateField(verbose_name="सम्पन्न मिति")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="सक्रिय (Active)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssuesAndRisks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("admin", "प्रशासनिक (Administrative)"),
                            ("financial", "आर्थिक (Financial)"),
                            ("technical", "प्राविधिक (Technical)"),
                            ("social", "सामाजिक (Social)"),
                            ("weather", "मौसम (Weather)"),
                            ("other", "अन्य (Other)"),
                        ],
                        max_length=20,
                        verbose_name="समस्याको प्रकार",
                    ),
                ),
                ("description", models.TextField(verbose_name="समस्याको विवरण")),
                (
                    "impact_on_cost",
                    models.BooleanField(default=False, verbose_name="लागतमा असर?"),
                ),
                (
                    "impact_on_time",
                    models.BooleanField(default=False, verbose_name="समयमा असर?"),
                ),
                (
                    "mitigation_plan",
                    models.TextField(blank=True, verbose_name="समाधानको उपाय"),
                ),
                (
                    "dpr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="core.dailyprogressreport",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DailyReport",
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="dpr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="core.dailyprogressreport",
            ),
        ),
        migrations.AddField(
            model_name="budgetprogram",
            name="fiscal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.fiscalyear",
                verbose_name="आर्थिक वर्ष",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.budgetprogram",
                verbose_name="बजेट कार्यक्रम (Program)",
            ),
        ),
    ]
