# Generated by Django 4.2 on 2026-01-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_budgetprogram_dailyactivity_dailyprogressreport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceDocs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="कागजातको नाम (Title)"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload Photos or PDFs",
                        upload_to="dpr_evidence/%Y/%m/",
                        verbose_name="कागजात (File)",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dpr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="core.dailyprogressreport",
                        verbose_name="प्रतिवेदन",
                    ),
                ),
            ],
        ),
    ]
