# Generated by Django 4.2 on 2026-01-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_evidencedocs"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyprogressreport",
            name="overall_physical_progress",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total Project Progress % up to this date",
                max_digits=5,
                verbose_name="समग्र भौतिक प्रगति (%)",
            ),
        ),
    ]
