# Generated by Django 5.2.10 on 2026-01-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_dailyprogressreport_overall_physical_progress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="allocation_source",
        ),
        migrations.RemoveField(
            model_name="budgetprogram",
            name="fiscal_year",
        ),
        migrations.RemoveField(
            model_name="project",
            name="budget_program",
        ),
        migrations.RemoveField(
            model_name="dailyactivity",
            name="dpr",
        ),
        migrations.AlterUniqueTogether(
            name="dailyprogressreport",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="dailyprogressreport",
            name="project",
        ),
        migrations.RemoveField(
            model_name="dailyprogressreport",
            name="reporting_officer",
        ),
        migrations.RemoveField(
            model_name="evidencedocs",
            name="dpr",
        ),
        migrations.RemoveField(
            model_name="issuesandrisks",
            name="dpr",
        ),
        migrations.RemoveField(
            model_name="project",
            name="expenditure_head",
        ),
        migrations.RemoveField(
            model_name="grievance",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="grievance",
            name="office",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="project",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="project",
            name="sub_sector",
        ),
        migrations.RemoveField(
            model_name="subsector",
            name="sector",
        ),
        migrations.DeleteModel(
            name="AllocationSource",
        ),
        migrations.DeleteModel(
            name="FiscalYear",
        ),
        migrations.DeleteModel(
            name="BudgetProgram",
        ),
        migrations.DeleteModel(
            name="DailyActivity",
        ),
        migrations.DeleteModel(
            name="EvidenceDocs",
        ),
        migrations.DeleteModel(
            name="DailyProgressReport",
        ),
        migrations.DeleteModel(
            name="IssuesAndRisks",
        ),
        migrations.DeleteModel(
            name="ExpenditureHead",
        ),
        migrations.DeleteModel(
            name="Grievance",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Sector",
        ),
        migrations.DeleteModel(
            name="SubSector",
        ),
    ]
