# Generated by Django 5.2.10 on 2026-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_remove_project_allocation_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "प्रणाली प्रशासक (System Admin)"),
                    ("user", "प्रयोगकर्ता (User)"),
                ],
                default="user",
                max_length=20,
                verbose_name="भूमिका",
            ),
        ),
    ]
