# Generated by Django 5.2.10 on 2026-01-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="office",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="office",
        ),
        migrations.DeleteModel(
            name="Office",
        ),
    ]
