# Generated by Django 4.2 on 2026-01-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_remove_contact_office_remove_notice_office_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video URL (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)",
                null=True,
                verbose_name="YouTube URL",
            ),
        ),
    ]
