# Generated by Django 5.2.9 on 2026-05-24 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_gallery_youtube_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="पूरा नाम"),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            (
                                "प्रमुख प्रशासकीय अधिकृत",
                                "प्रमुख प्रशासकीय अधिकृत (CAO)",
                            ),
                            ("प्रमुख (CEO)", "प्रमुख (CEO)"),
                            ("सूचना अधिकारी", "सूचना अधिकारी (Suchana Adhakari)"),
                            ("गुनासो अधिकारी", "गुनासो अधिकारी (Gunaso Adhakari)"),
                            ("लेखा अधिकृत", "लेखा अधिकृत"),
                            ("कानून अधिकृत", "कानून अधिकृत"),
                            ("प्राविधिक अधिकृत", "प्राविधिक अधिकृत"),
                            ("वडा अध्यक्ष", "वडा अध्यक्ष"),
                            ("अन्य", "अन्य (Other)"),
                        ],
                        max_length=100,
                        verbose_name="पद",
                    ),
                ),
                (
                    "custom_designation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="कस्टम पद (अन्य भएमा)"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, verbose_name="फोन नं."),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="इमेल"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="representatives/",
                        verbose_name="फोटो",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="क्रम")),
                ("is_active", models.BooleanField(default=True, verbose_name="सक्रिय")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="सिर्जनाकर्ता",
                    ),
                ),
            ],
            options={
                "verbose_name": "प्रतिनिधि / पदाधिकारी",
                "verbose_name_plural": "प्रतिनिधिहरू / पदाधिकारीहरू",
                "ordering": ["order", "full_name"],
            },
        ),
    ]
